### PR TITLE
Rewrite getStreamData and associated functions

### PR DESCRIPTION
**Pull request by dkarchmer**
To properly get all pages and wait until ALL data is fetched.
It works by first getting a click 10 data entry GET just to get the
total count, and use that to calculate the number of pages to fetch.
Then use forkJoin to get them all

### CODE REVIEW

**Comment by dkarchmer** [comment]
@timburke Can I ask you to review this change, mostly to get your opinion.

The diff is hard to review, so I suggest you just look at the following function:

```
public getAllStreamData(stream: Stream, args: DataFilterArgs): ReplaySubject<any>  {

    // Uses getPointCount to get 10 entries, just to get a total count.
    // It then uses that total count to calculate the number of total pages
    // needed to fetch ALL entries, and generates a forkJoin with all GETs (getData)
    // This ensures the function won't return results until all GETs return
    // Each getData call returns a dataPage with the results for that page fetch
    let returnedData = new ReplaySubject(1);

    let urlBase: string = '/stream/' + stream.slug + '/data/';
    let url: string = urlBase + args.buildFilterString();
    console.debug('[CloudService] getAllData ====> ' + url);
    this.getPointCount(url).subscribe(
      count => {

        // Reset pageSize to the default size to get proper sized data pages
        args.pageSize = 1000;
        let dataUrl = urlBase + args.buildFilterString();
        let pageCount = Math.ceil(count / args.pageSize);
        console.debug('No. of pages (to be forkJoin-ed): ' + args.pageSize + '/' + count + '=' + pageCount);
        let observables = [];

        let dataPages: Array<DataPage> = [];
        for (let i = 1; i <= pageCount; i++) {
          dataPages[i] = new DataPage(dataUrl, i, pageCount, stream);
          observables.push(this.getSingleDataPage(dataPages[i]));
        }
        let firstObservable = Observable.forkJoin(observables);
        firstObservable.subscribe(
          allData => {
            let totalCount = 0;
            for (let key in allData) {
              let dataPage = allData[key] as DataPage;

              dataPage.data.forEach(item => {
                dataPage.stream.data.push(item);
                totalCount++;
              });
              console.log('Page ' + dataPage.page + ' for ' + dataPage.stream.slug + ': ' + totalCount);
            }
            returnedData.next(totalCount);
          });
      },
      err => {
        console.error(err);
        returnedData.error(err);
      }
    );
    return returnedData;
  }
```

**Comment by dkarchmer** [comment]
Still need to figure out how to test iotile.service, but I have not been able to figure out how to mock the http service.

**Comment by timburke** [comment]
My one concern was whether `forkJoin` guaranteed to return the pages in order but it looks like it does.  In the future we're going to need to add another layer on top of this where we don't just pass 20k points to our charting library but smartly resample the graph based on how closely spaced the points are so that it remains fast even with large time range queries. 

That's a feature for another time though

**Comment by dkarchmer** [comment]
Yes, I was explaining to Andrew and Tallis that we may need to sample data and store multiple sampled charts (equivalent to how web sites store multiple sized images/videos). So every hour, a cron job will summarize the last hour of data and add one entry to the perDay table, and every week, to the perWeek, and so on. Otherwise, I think it will be too computationally intensive for the server to do that real time.
The problem I have is that knowing how to unify the data may be application specific. How do you know if you should add all points in the hour, or average them, or get the max or the min. We would need a way to represent that meta data.

**Pull request merged**
