### PR TITLE
Update Membership Model and add Permissions Model

### LINKED ISSUE #106: Update Member model to have `permissions` field
Related to iotile/app.iotile.cloud#617

### PR DESCRIPTION
**Pull request by lekosfmi**
resolve #106 
related to iotile/app.iotile.cloud#617

### CODE REVIEW

**Comment by lekosfmi** [comment]
A Permission object that looks like this?
```
class Permission {
  s0: {
    // Can delete Org
    can_delete_org: boolean;

    // Can Invite and delete members, and change member attributes
    can_manage_users: boolean;

    // Can manage Fleets and OTA Deployments
    can_manage_ota: boolean;

    // Can Create, Delete and modify Projects (including project properties)
    can_manage_org_and_projects: boolean;
    
    // Can Claim devices into Org projects
    can_claim_devices: boolean;
    ...
  }
}
```

**Comment by dkarchmer** [comment]
No, a normal TypeScript class that looks like:

```
class Permission {
  // Can Invite and delete members, and change member attributes
  public canManageUsers: boolean;

  // Can Create, Delete and modify Projects (including project properties)
  public canManageOrgsAndProjects: boolean

  ...

  constructor(data: any = {}) {
       this.canManageUsers = data['can_manage_users'];
       ....
  }
}
```

(Always follow TypeScypt/JavaScript variable name standards when creating classes).

At this point, we only need:

```
    # Can Invite and delete members, and change member attributes
    'can_manage_users',
    # Can manage Fleets and OTA Deployments
    'can_manage_ota',
    # Can Create, Delete and modify Projects (including project properties)
    'can_manage_org_and_projects',
    # Can Claim devices into Org projects
    'can_claim_devices',
    # Can modify device information, including properties
    'can_modify_device',
    # Can view device properties
    'can_read_device_properties',
    # Can modify device properties
    'can_modify_device_properties',
    # Can read notes
    'can_read_notes',
    # Can access Device Location
    'can_read_device_locations',
    # Can read stream data and events
    'can_read_stream_data',
    # Can upload streamer reports
    'can_upload_streamer_report',
    # Can manually post stream data and events via JSON POST API
    'can_create_stream_data',
    # Can archive Device data
    'can_create_datablock',
    # Can access Archived data
    'can_access_datablock',

    # Can access Org pages from WebApp
    'can_access_webapp',
```

**Comment by dkarchmer** [comment]
You can also add the permission role name, but that actually has no meaning, and will only be needed when you allow admins (`can_manage_users`) to change roles. Otherwise, it should never be used for anything

**Comment by lekosfmi** [comment]
So the `Permission` class will only contain key-value of the permissions retrieved from the cloud?

**Comment by dkarchmer** [comment]
Yes, that is all the API gives you access to. The difference with your original PR is that you will be explicitly reading the permissions that make sense, and ignoring others. And you will be documenting these permissions.

**Comment by dkarchmer** [comment]
But as I also said, I will like to understand how are you planning for every page in the app to get access to these Member object?

**Comment by lekosfmi** [comment]
Can we have time to discuss how every page could obtain access to the `Member` object?

**Comment by dkarchmer** [comment]
Also remove: 

    'can_upload_streamer_report',

**Pull request merged**
